### ISSUE TITLE
Bullets/shells dissapearing well before the physics load range

### ISSUE THREAD

**Issue by boomchacle** [BahamutoD/BDArmory#32] opened 2016-03-17 04:00 UTC
when I fire a gun, like the howitzer at a very long distance, the shell will always disappear before it gets to the target. It also always will disappear at the same place. I want to know if they have a different load range for bullets, and, if you can change it, because the physics load range does nothing.

**Comment by Shuudoushi** [comment] 2016-03-17 07:14
Going to need some specs from you. Like OS, if the game is being forced to run in 64-bit mode on windows (I've ran into this issue in 64-bit, but just chalked it up to 64-bit oddness), other mods that screw with stuff (FAR is a good example, but it alone shouldn't cause any issues), ect.

**Comment by boomchacle** [comment] 2016-03-19 01:34
I do have a 64 bit computer and I have an NVS 5200M GPU

**Comment by Shuudoushi** [comment] 2016-03-19 03:12
How far away is the target you are trying to hit? (A lot of rounds [including the 105] have a max range)

**Comment by boomchacle** [comment] 2016-03-19 05:33
I wanted to have a long range naval battle, but the rounds dissapeared after about 10 km

**Comment by Shuudoushi** [comment] 2016-03-19 08:18
Yeah... Most of the weapons that use cannon shells have a max range of 8 clicks. You can simply go into the configs to change this for the weapons you intend to use.

I.e. This is intended behavior and not a bug of some sort.

**Comment by Shuudoushi** [comment] 2016-03-19 08:25
`<game path>\GameData\BDArmory\Parts\m1Abrams` lines 80-81:

`maxTargetingRange = 8000`
`maxEffectiveDistance = 8000`

Bump these two out to whatever you want and all should work fine.

Do note, that this can start to cause oddness and that I am in no way responsible if your computer catches on fire or eats your dog or something.

**Comment by boomchacle** [comment] 2016-03-21 00:05
For some reason, I am unable to change config files...

**Comment by Shuudoushi** [comment] 2016-03-21 00:12
Simply opening them with notepad++ or w/e should work just fine...

**Comment by boomchacle** [comment] 2016-03-21 06:59
thanks that helped

**Comment by Shuudoushi** [comment] 2016-03-21 17:22
If the issue is solved, would you mind closing this issue.

**Comment by boomchacle** [comment] 2016-03-22 03:02
lol I used that software to do other ridiclous stuff to the bombs and cannon, like have a howitzer with no recoil firing 6000 rpm.

**Closed as completed** 2016-03-22 04:28 UTC
